# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/haro/Documents/GitHub/16-Bits-de-Historia

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/haro/Documents/GitHub/16-Bits-de-Historia

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/haro/Documents/GitHub/16-Bits-de-Historia/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/haro/Documents/GitHub/16-Bits-de-Historia/CMakeFiles /home/haro/Documents/GitHub/16-Bits-de-Historia//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/haro/Documents/GitHub/16-Bits-de-Historia/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 16-Bits_de_Historia

# Build rule for target.
16-Bits_de_Historia: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 16-Bits_de_Historia
.PHONY : 16-Bits_de_Historia

# fast build rule for target.
16-Bits_de_Historia/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/build
.PHONY : 16-Bits_de_Historia/fast

#=============================================================================
# Target rules for targets named raylib

# Build rule for target.
raylib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raylib
.PHONY : raylib

# fast build rule for target.
raylib/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/raylib/CMakeFiles/raylib.dir/build.make _deps/raylib-build/raylib/CMakeFiles/raylib.dir/build
.PHONY : raylib/fast

src/components/animation.o: src/components/animation.c.o
.PHONY : src/components/animation.o

# target to build an object file
src/components/animation.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/animation.c.o
.PHONY : src/components/animation.c.o

src/components/animation.i: src/components/animation.c.i
.PHONY : src/components/animation.i

# target to preprocess a source file
src/components/animation.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/animation.c.i
.PHONY : src/components/animation.c.i

src/components/animation.s: src/components/animation.c.s
.PHONY : src/components/animation.s

# target to generate assembly for a file
src/components/animation.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/animation.c.s
.PHONY : src/components/animation.c.s

src/components/cine.o: src/components/cine.c.o
.PHONY : src/components/cine.o

# target to build an object file
src/components/cine.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/cine.c.o
.PHONY : src/components/cine.c.o

src/components/cine.i: src/components/cine.c.i
.PHONY : src/components/cine.i

# target to preprocess a source file
src/components/cine.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/cine.c.i
.PHONY : src/components/cine.c.i

src/components/cine.s: src/components/cine.c.s
.PHONY : src/components/cine.s

# target to generate assembly for a file
src/components/cine.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/cine.c.s
.PHONY : src/components/cine.c.s

src/components/debug.o: src/components/debug.c.o
.PHONY : src/components/debug.o

# target to build an object file
src/components/debug.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/debug.c.o
.PHONY : src/components/debug.c.o

src/components/debug.i: src/components/debug.c.i
.PHONY : src/components/debug.i

# target to preprocess a source file
src/components/debug.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/debug.c.i
.PHONY : src/components/debug.c.i

src/components/debug.s: src/components/debug.c.s
.PHONY : src/components/debug.s

# target to generate assembly for a file
src/components/debug.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/debug.c.s
.PHONY : src/components/debug.c.s

src/components/enemy.o: src/components/enemy.c.o
.PHONY : src/components/enemy.o

# target to build an object file
src/components/enemy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/enemy.c.o
.PHONY : src/components/enemy.c.o

src/components/enemy.i: src/components/enemy.c.i
.PHONY : src/components/enemy.i

# target to preprocess a source file
src/components/enemy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/enemy.c.i
.PHONY : src/components/enemy.c.i

src/components/enemy.s: src/components/enemy.c.s
.PHONY : src/components/enemy.s

# target to generate assembly for a file
src/components/enemy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/enemy.c.s
.PHONY : src/components/enemy.c.s

src/components/keybinds.o: src/components/keybinds.c.o
.PHONY : src/components/keybinds.o

# target to build an object file
src/components/keybinds.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/keybinds.c.o
.PHONY : src/components/keybinds.c.o

src/components/keybinds.i: src/components/keybinds.c.i
.PHONY : src/components/keybinds.i

# target to preprocess a source file
src/components/keybinds.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/keybinds.c.i
.PHONY : src/components/keybinds.c.i

src/components/keybinds.s: src/components/keybinds.c.s
.PHONY : src/components/keybinds.s

# target to generate assembly for a file
src/components/keybinds.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/keybinds.c.s
.PHONY : src/components/keybinds.c.s

src/components/level.o: src/components/level.c.o
.PHONY : src/components/level.o

# target to build an object file
src/components/level.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/level.c.o
.PHONY : src/components/level.c.o

src/components/level.i: src/components/level.c.i
.PHONY : src/components/level.i

# target to preprocess a source file
src/components/level.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/level.c.i
.PHONY : src/components/level.c.i

src/components/level.s: src/components/level.c.s
.PHONY : src/components/level.s

# target to generate assembly for a file
src/components/level.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/level.c.s
.PHONY : src/components/level.c.s

src/components/menu.o: src/components/menu.c.o
.PHONY : src/components/menu.o

# target to build an object file
src/components/menu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/menu.c.o
.PHONY : src/components/menu.c.o

src/components/menu.i: src/components/menu.c.i
.PHONY : src/components/menu.i

# target to preprocess a source file
src/components/menu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/menu.c.i
.PHONY : src/components/menu.c.i

src/components/menu.s: src/components/menu.c.s
.PHONY : src/components/menu.s

# target to generate assembly for a file
src/components/menu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/menu.c.s
.PHONY : src/components/menu.c.s

src/components/npc.o: src/components/npc.c.o
.PHONY : src/components/npc.o

# target to build an object file
src/components/npc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/npc.c.o
.PHONY : src/components/npc.c.o

src/components/npc.i: src/components/npc.c.i
.PHONY : src/components/npc.i

# target to preprocess a source file
src/components/npc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/npc.c.i
.PHONY : src/components/npc.c.i

src/components/npc.s: src/components/npc.c.s
.PHONY : src/components/npc.s

# target to generate assembly for a file
src/components/npc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/npc.c.s
.PHONY : src/components/npc.c.s

src/components/object.o: src/components/object.c.o
.PHONY : src/components/object.o

# target to build an object file
src/components/object.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/object.c.o
.PHONY : src/components/object.c.o

src/components/object.i: src/components/object.c.i
.PHONY : src/components/object.i

# target to preprocess a source file
src/components/object.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/object.c.i
.PHONY : src/components/object.c.i

src/components/object.s: src/components/object.c.s
.PHONY : src/components/object.s

# target to generate assembly for a file
src/components/object.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/object.c.s
.PHONY : src/components/object.c.s

src/components/player.o: src/components/player.c.o
.PHONY : src/components/player.o

# target to build an object file
src/components/player.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/player.c.o
.PHONY : src/components/player.c.o

src/components/player.i: src/components/player.c.i
.PHONY : src/components/player.i

# target to preprocess a source file
src/components/player.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/player.c.i
.PHONY : src/components/player.c.i

src/components/player.s: src/components/player.c.s
.PHONY : src/components/player.s

# target to generate assembly for a file
src/components/player.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/player.c.s
.PHONY : src/components/player.c.s

src/components/sound.o: src/components/sound.c.o
.PHONY : src/components/sound.o

# target to build an object file
src/components/sound.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/sound.c.o
.PHONY : src/components/sound.c.o

src/components/sound.i: src/components/sound.c.i
.PHONY : src/components/sound.i

# target to preprocess a source file
src/components/sound.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/sound.c.i
.PHONY : src/components/sound.c.i

src/components/sound.s: src/components/sound.c.s
.PHONY : src/components/sound.s

# target to generate assembly for a file
src/components/sound.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/components/sound.c.s
.PHONY : src/components/sound.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/16-Bits_de_Historia.dir/build.make CMakeFiles/16-Bits_de_Historia.dir/src/main.c.s
.PHONY : src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... 16-Bits_de_Historia"
	@echo "... raylib"
	@echo "... src/components/animation.o"
	@echo "... src/components/animation.i"
	@echo "... src/components/animation.s"
	@echo "... src/components/cine.o"
	@echo "... src/components/cine.i"
	@echo "... src/components/cine.s"
	@echo "... src/components/debug.o"
	@echo "... src/components/debug.i"
	@echo "... src/components/debug.s"
	@echo "... src/components/enemy.o"
	@echo "... src/components/enemy.i"
	@echo "... src/components/enemy.s"
	@echo "... src/components/keybinds.o"
	@echo "... src/components/keybinds.i"
	@echo "... src/components/keybinds.s"
	@echo "... src/components/level.o"
	@echo "... src/components/level.i"
	@echo "... src/components/level.s"
	@echo "... src/components/menu.o"
	@echo "... src/components/menu.i"
	@echo "... src/components/menu.s"
	@echo "... src/components/npc.o"
	@echo "... src/components/npc.i"
	@echo "... src/components/npc.s"
	@echo "... src/components/object.o"
	@echo "... src/components/object.i"
	@echo "... src/components/object.s"
	@echo "... src/components/player.o"
	@echo "... src/components/player.i"
	@echo "... src/components/player.s"
	@echo "... src/components/sound.o"
	@echo "... src/components/sound.i"
	@echo "... src/components/sound.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

